stages:
    - build

build:
    stage: build
    image: node:lts
    script:
        - npm i -g testfairy-unity-asset-packager
        - testfairy-unity-asset-packager
          -o TivoliAvatarExporter.unitypackage
          -p Assets/Editor/TivoliAvatarExporter .
    artifacts:
        expire_in: 1 day
        paths:
            - TivoliAvatarExporter.unitypackage
